### ISSUE TITLE
minor correction & ajax

### ISSUE THREAD

**Issue by rharsh** [redlab/bootstrap-ext#4]
minor correction, the option

this.items = this.options.items

is missing in the JS file. Hence if more than one typeaheadmap then the last items is taken

Also how about an ajax functionality. Do not think it would be a major change since almost everything is in place

**Comment by redlab** [comment]
Hi rharsh
I just tested your submission.

I wonder how you're using typeaheadmap and in what browser, There is no need to do 

``` javascript
this.items = this.options.items
```

 since items is always used from this.options

``` javascript
this.render(items.slice(0, this.options.items)).show()
```

Check the demo http://redlab.github.com/bootstrap-ext/typeaheadmap.html you can see that both input fields show a different amount of values.

**Comment by redlab** [comment]
And concerning AJAX

That is already possible. You can pass a function as 'source' that function will receive 2 parameters, the typed input and the process function. With the typed input you can fetch the needed data from your server and pass it to the process function. Something like the pseudo code under here 

``` javascript
"source" : function(q, process) { 
     $.ajax({url: yourfetchurl+'?q='+q, 
               dataType: 'json',
               success: function(data) { process(fetcheddata)  }
     })
},
```
