### ISSUE TITLE
Delay/debounce option

### ISSUE THREAD

**Issue by mdi** [redlab/bootstrap-ext#5]
It would be nice to have some sort of delay/debounce option for this to prevent too many requests being generated. Or is there an easy way to add this without the need for an option?

**Comment by redlab** [comment]
I assume this is when you use an ajax request that returns the needed values in the source function, since your talking about a request?

You could try to add this in your override of the source function, then there is no need for an option. 
To add is as an option would require some work and I can't promise a date when that will be done. It's not a bad idea though!

**Comment by redlab** [comment]
Closing, out of scope. Feel free to send pull request :-)

**Comment by redlab** [comment]
Closed, out of scope. Feel free to send pullrequest
